### ISSUE TITLE
非常感谢分享，已经全部装好，等周末开始开机测试。提一个小建议。

### ISSUE THREAD

**Issue by winter07** [axlzys/KH-Tester#2]
建议把R300电机做高一点，磁铁和转子之间的空间比较大。电机上的那块3D模块可以做小一点，转子两头不能很好的吸住。我现在用的是KHG的模块，大小还是比较合适的。反应盒的材料还能换成别的吗？我担心3D打印的用久了会漏

**Comment by axlzys** [comment]
> 

我一开始用的pla会渗，后来用了petg，顶层5 走线3，目前一直没漏，，
