### ISSUE TITLE
Tritation and Reagent Pump

### ISSUE THREAD

**Issue by luksmbf** [axlzys/KH-Tester#5]
Hi, I saw that you use 4 dosing pumps, and I'm a bit confuse about what one of them does (specifically the third one - titration). Below I described what I understood for what each pump do, please check my understanding.
- The first dosing pump, pumps water form the tank to the chamber.
- The second dosing pump, pumps water from the chamber to a resevoir or back to the tank after the test is complete.
- The third pump is called titration pump but I did not understand what ir pumps (from where to where).
- The fourth pump pumps the reagent hydrochloric acid to the chamber.

I'm going to try rebuild the eletronics and software of this project to use an ESP32.
Could you also check if my understanding of the test process (below).
1 - Pump water from tank to reaction chamber, checking it level.
2 - Check initial PH.
3 - Dose some  hydrochloric acid to reaction chamber.
4 - Stirr the liquid in chamber.
5 - Verify if the PH reached 4.
6 - Do the steps 3, 4 and 5 until gets PH to 4.
7 - Calculate PH.
8 - Pump the liquid out of the chamber.

**Comment by axlzys** [comment]
The third pump is for KH balance,but it's dont work now.i have no time to finsh the cord.
The earliest idea was Set the target KH value first,and comparison of KH value and target value after each test,then add some KH buffer,until the test result is close to the target value.
about the test process:
1.clean the reaction chamber(include pump water from tank,Stirring reaction chamber,pump the liquid out)
2.pump the water from tank again.it's Always checks PH every 10 seconds.
3.Dose some hydrochloric acid to reaction chamber.Stirring during doseing hydrochloric acid.
4.when it's doseing,the PH will check after every hydrochloric acid dorps.until the PH<=4.5.
5.Calculate PH.(in that process if you set KH target,it Will decide whether to add KH buffer according to the value.but the code don't work now,The motor pins are wrong in the code)
6.Pump the liquid out.
7.pump water from tank to reaction chamber.

**Comment by luksmbf** [comment]
Thank you very much for the explanation!
